name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '*.md'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.1.21458.32

    - name: Pack
      run: dotnet pack Vortice.sln --configuration Release --output build/packages

    - name: Publish to NuGet
      if: github.event_name == 'push'
      run: |      
          if ( "${{github.ref}}" -match "^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$" ) {
              dotnet nuget push build/packages/**/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
